#
# https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md
#

dist: trusty
branches:
  only:
    - master
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  - ETHBRIDGE=1
  - ETHRELAY=1
  - NEARBRIDGE=1
  - NEARBRIDGE_LINT=1
  - NEARBRIDGE_COVERAGE=1
  - NEARRELAY=1
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13;
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157;
      curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -;
      sudo apt-get install -y nodejs;
      curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -;
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list;
      sudo apt-get update && sudo apt-get install yarn;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
      then brew install node@10 yarn;
    fi
  - echo "Node:"
  - node --version
  - if [ "$ETHBRIDGE" = "1" ]; then
      cd ./ethbridge;
      ./test.sh;
    fi
  - if [ "$ETHRELAY" = "1" ]; then
      cd ./ethbridge;
      rustup target add wasm32-unknown-unknown --toolchain $(rustup toolchain list | cut -d- -f1);
      ./build.sh;
      cd ../ethrelay/ethashproof;
      eval "$(gimme 1.12)";
      go version;
      ./build.sh;
      cd ..;
      yarn && yarn run test;
    fi
  - if [ "$NEARBRIDGE" = "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run test;
      yarn run codechecks;
    fi
  - if [ "$NEARBRIDGE_LINT" = "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run lint;
    fi
  - if [ "$NEARBRIDGE_COVERAGE" = "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run coverage && cat coverage/lcov.info | coveralls;
    fi
  - if [ "$NEARRELAY" = "1" ]; then
      cd ./ethbridge;
      rustup target add wasm32-unknown-unknown --toolchain $(rustup toolchain list | cut -d- -f1);
      ./build.sh;
      cd ../nearrelay;
      yarn && yarn run test;
    fi
