#
# https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md
#

sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
env:
  - ETHBRIDGE=1
  - ETHRELAY=1
  - NEARBRIDGE=1
  - NEARBRIDGE_LINT=1
  - NEARBRIDGE_COVERAGE=1
  - NEARRELAY=1
script:
  - if [ $ETHBRIDGE == "1" ]; then
      cd ./ethbridge;
      sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y && export PATH=$PATH:~/.cargo/bin;
      rustup toolchain install stable;
      rustup default stable;
      rustup target add wasm32-unknown-unknown --toolchain stable;
      ./test.sh;
    fi
  - if [ $ETHRELAY == "1" ]; then
      cd ./ethbridge;
      sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y && export PATH=$PATH:~/.cargo/bin;
      rustup toolchain install stable;
      rustup default stable;
      rustup target add wasm32-unknown-unknown --toolchain stable;
      ./build.sh;
      cd ../ethrelay/ethashproof;
      bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer);
      echo "===aaa"
      source ~/.gvm/scripts/gvm;
      echo "===bbb"
      gvm install go1.12;
      echo "===ccc"
      gvm use go1.12 --default;
      ./build.sh;
      cd ..;
      yarn && yarn run test;
    fi
  - if [ $NEARBRIDGE == "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run test;
      npx codechecks;
    fi
  - if [ $NEARBRIDGE_LINT == "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run lint;
    fi
  - if [ $NEARBRIDGE_COVERAGE == "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run coverage && cat coverage/lcov.info | coveralls;
    fi
  - if [ $NEARRELAY == "1" ]; then
      cd ./ethbridge;
      sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y && export PATH=$PATH:~/.cargo/bin;
      rustup toolchain install stable;
      rustup default stable;
      rustup target add wasm32-unknown-unknown --toolchain stable;
      ./build.sh;
      cd ../nearrelay;
      yarn && yarn run test;
    fi
