#
# https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md
#

sudo: required
dist: trusty
node_js:
  - '10'
script:
  - echo "NearBridge:"
  - cd ./nearbridge
  - yarn && yarn run lint && yarn run test
  - yarn run coverage && cat coverage/lcov.info | coveralls
  - echo "EthBridge:"
  - cd ../ethbridge
  - cargo test --package eth-bridge --features env_test -- --nocapture
branches:
  only:
  - master
