#
# https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md
#

dist: trusty
branches:
  only:
    - master
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  - ETHBRIDGE=1
  - ETHRELAY=1
  - NEARBRIDGE=1
  - NEARBRIDGE_LINT=1
  - NEARBRIDGE_COVERAGE=1
  - NEARRELAY=1
script:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - nvm install 10.19.0
  - nvm use 10.19.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - echo "Node:"
  - node --version
  - echo "Yarn:"
  - yarn --version
  - if [ "$ETHBRIDGE" = "1" ]; then
      cd ./ethbridge;
      ./test.sh;
    fi
  - if [ "$ETHRELAY" = "1" ]; then
      cd ./ethbridge;
      rustup target add wasm32-unknown-unknown --toolchain $(rustup toolchain list | cut -d- -f1);
      ./build.sh;
      cd ../ethrelay/ethashproof;
      eval "$(gimme 1.12)";
      go version;
      ./build.sh;
      cd ..;
      yarn && yarn run test;
    fi
  - if [ "$NEARBRIDGE" = "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run test;
      yarn run codechecks;
    fi
  - if [ "$NEARBRIDGE_LINT" = "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run lint;
    fi
  - if [ "$NEARBRIDGE_COVERAGE" = "1" ]; then
      cd ./nearbridge;
      yarn;
      yarn run coverage && cat coverage/lcov.info | yarn run coveralls;
    fi
  - if [ "$NEARRELAY" = "1" ]; then
      cd ./ethbridge;
      rustup target add wasm32-unknown-unknown --toolchain $(rustup toolchain list | cut -d- -f1);
      ./build.sh;
      cd ../nearrelay;
      yarn && yarn run test;
    fi
