#
# https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md
#

sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
script:
  - echo "NearBridge:"
  - cd ./nearbridge
  - yarn && yarn run lint && yarn run test && npx codechecks
  - yarn run coverage && cat coverage/lcov.info | coveralls
  - echo "EthBridge:"
  - cd ../ethbridge
  - sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y && export PATH=$PATH:~/.cargo/bin
  - rustup toolchain install nightly
  - rustup default nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - ./test.sh
branches:
  only:
  - master
